### PR TITLE
Feature/fix flake8 errors

### PR DESCRIPTION
**Pull request by petervanderdoes**
- Corrected all Flake8 errors
- Sorted and combined the imports.
- Imports are organized by usage, Standard Library, Third Party, wger

### Important Information
The file `package.json` has been moved from the `wger` directory to the root of project. In order to use gulp it's best to have this file in the root pf the project.

### CODE REVIEW

**Comment by petervanderdoes** [comment]
Adding the ability to check the modules import using `isort` and `gulp`.

### Requirements
- `pip install -r requirements_devel.txt`
- `npm install`

### Gulp commands
- `gulp lint-js`  
Lint the javascript files using eslint
- `gulp lint-flake8`  
Lint the python files using flake8 and flake8-putty
- `gulp lint-isort`
Check if the modules are sorted in order
- `gulp`  
Runs `gulp-js` and `gulp-flake8`. I left out `gulp-isort` for now.

**Comment by petervanderdoes** [comment]
When we merge this PR we will also need to update the file `wger/docs/development.rst` to reflect the new options and requirements.

**Comment by rolandgeider** [comment]
Thanks, that was a lot of work! We should also add a contributing.md file and roughly explain what linters are active, plus a link to the appropriate places in the documentation

**Comment by rolandgeider** [comment]
Merged, I'll update the docs

**Pull request merged**
