### PR TITLE
Allow start of exercise crowdsourcing branch

### PR DESCRIPTION
**Pull request by ImTheTom**
# Proposed Changes
- Was trying to start the branch fresh going through the steps in https://wger.readthedocs.io/en/latest/development.html found myself triggering errors until I made the following changes.
- Also fixes the comments tests
- Found some migrations that didn't have a file for while running `python manage.py makemigrations exercises`

## Please check that the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Added yourself to AUTHORS.rst

### Other questions

* Do users need to run some commmands in their local instances due to this PR
  (e.g. database migration)? Yes
* Do you have any tips on how to create dynamic dates and datetimes for the fixtures.
* I can see you have been working on this branch recently. Is there something I'm missing to allow start up of the branch without these changes?

### CODE REVIEW

**Comment by ImTheTom** [comment]
Oh, one reason why it was so hard for me to start was the fact my branch was old 🤦

**Comment by rolandgeider** [comment]
Oh damn, I hadn't thought that the fixtures and stuff like weren't updated. What you can do is take a database.sqlite file from master and run the migrations form this branch

**Comment by rolandgeider** [comment]
You can also write me ob discord if you run into such problems 😅

**Comment by ImTheTom** [comment]
Oh chill. I'll start again and make sure my branch is fully updated.

**Pull request closed without merging**
