### PR TITLE
Add progress bar to load-online-fixtures

### PR DESCRIPTION
**Pull request by ebwinters**
# Proposed Changes
Adding a progress bar to `load-online-fixtures` command since it is unclear if progress is happening and leads to confusion when running the command as mentioned in [this issue from the docker repo](https://github.com/wger-project/docker/issues/76) 
- Use tqdm package
- Track progress on json download
- Use custom `loaddata` implementation to track progress on `loaddata` command
image

## Please check that the PR fulfills these requirements

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Added yourself to AUTHORS.rst

### Other questions

* Do users need to run some commmands in their local instances due to this PR
  (e.g. database migration)?
No

### CODE REVIEW

**Comment by rolandgeider** [comment]
Good idea! This could also be useful for other commands like the one that syncs exercises and so. However the download itself is not what takes so long, loading the zip file needs some time as well, but adding some prints after this should at least make clear that things are happening

**Comment by ebwinters** [comment]
@rolandgeider  custom load data handles showing progress on fixture load

**Comment by rolandgeider** [comment]
it does? when I tried it it showed immediately 1/1 and then nothing

**Comment by ebwinters** [comment]
Yeah if you give it a minute to begin that process, it will print progress for both stages (download and dump).

**Comment by rolandgeider** [comment]
This is what I mean, this jumps to 1/1 and then it needs some time to actually import the fixtures: 

Bildschirmfoto 2024-01-23 um 19 58 58

**Comment by ebwinters** [comment]
@rolandgeider  here is what I see
image

So is it not actually tracking fixture import progress correctly?

**Comment by rolandgeider** [comment]
Yes that's what I mean, I'd expect it to show the detailed progress of the import (like processed x/86731 objects)

**Comment by rolandgeider** [comment]
oh wait, doing `loaddata --verbosity=3` does exactly that

**Comment by ebwinters** [comment]
Should I make another pr to default that verbosity?

**Comment by rolandgeider** [comment]
I just commited it 😄

**Pull request merged**
