### PR TITLE
Allow user to give meals a description 

### PR DESCRIPTION
**Pull request by Gr8ayu**
Allow user to give meals a description/name such as breakfast or after workout
resolving #773 

# Proposed Changes

- add name field to meal model class 
- add 'name' in MealSerializer
- add 'name' in MealInfoSerializer

## Please check that the PR fulfills these requirements

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Added yourself to AUTHORS.rst

### Other questions

* Do users need to run some commmands in their local instances due to this PR
  (e.g. database migration)?
YES

### CODE REVIEW

**Comment by rolandgeider** [comment]
That was quick 😄

Can you commit the migration file as well? Also, we should show the meal name in the template

**Comment by Gr8ayu** [comment]
yeah I'll add those migrations, and by template you mean frontend right ?

**Comment by rolandgeider** [comment]
Yes

**Comment by rolandgeider** [comment]
And the last thing we need to do: add the new field to the list of fields in the forms in `MealCreateView` and `MealEditView`, otherwise it would not be possible to set it

**Comment by Gr8ayu** [comment]
image

I've added meal name like this in the template

**Comment by Gr8ayu** [comment]
> And the last thing we need to do: add the new field to the list of fields in the forms in `MealCreateView` and `MealEditView`, otherwise it would not be possible to set it

Okay

**Comment by rolandgeider** [comment]
Great, thanks!

**Pull request merged**
