### PR TITLE
[Bugfix] d3 v4 bmi chart problem

### PR DESCRIPTION
**Pull request by petervanderdoes**
After upgrading the D3 library to v4 the BMI did not work anymore due to changes between v3 and v4. For a complete list of changes see: https://github.com/d3/d3/blob/master/CHANGES.md

### CODE REVIEW

**Comment by petervanderdoes** [comment]
The check for Python 3.5 failed with:

`The command "curl -s -o python-3.5.tar.bz2 ${archive_url}" failed and exited with 18 during .`

Don't know why that happened.

**Comment by rolandgeider** [comment]
Sometimes the CI has such strange errors, if it doesn't happen in all builds, it's OK to just ignore them.

Besides that thanks for the PR, I know that my D3 code is really ugly... :angel:  I'll test it this evening and merge it

**Comment by petervanderdoes** [comment]
Don't worry about the D3 code, I had never done anything with D3 before this PR. It was crazy to find v4 code that could do what we wanted, quiet a bit a trial and error on my side.

On a side note, I know you want Python to be PEP8 formatted, do you have a preference for Javascript? Like AirBnB, Google.....? Want to add eslint for javascript? I could do a new PR for that if you want it.

**Comment by petervanderdoes** [comment]
Ugh, tried to rebase the bugfix branch with the changes of the deprecated changes merged already.

**Comment by rolandgeider** [comment]
Hehe, you couldn't wait! (In case you did it so that there are less merges, I don't care about them, I know that it's kind of the _git way_, but I think they are important ant just show how the development took place). In any case, I just tested this and everything seems to be working again

**Comment by rolandgeider** [comment]
As for adding some linter for JS, yeah, that would be great. If you add it, can you add it to the rest of the travis checks?

BTW, have you any experience with angular2?

**Comment by petervanderdoes** [comment]
No experience with angular2, I'll open a new issue for the style guide of Javascript.

**Pull request merged**
