### PR TITLE
Feature/bmi on graph at weight overview (Issue #462)

### PR DESCRIPTION
**Pull request by Svn-Sp**
Maybe the most hacky thing I ever did... 
There is no inbuilt function for custom ticks, so I had to make the code calculate the correct positions of the bmi lines manually.
The only thing I have not figured out yet is how to give the lines a different color. I do not know why, but ```setAttributeNS(null, "stroke", "red")``` does not work...

### CODE REVIEW

**Comment by rolandgeider** [comment]
> Maybe the most hacky thing I ever did...

OMG you weren't kidding! 😂

I'll take some time tomorrow or so to look at it

**Comment by rolandgeider** [comment]
I've been looking around the docs of metricsgraphics (which doesn't seem to be maintained so well at the moment BTW) for a graph for the new nutrition diary. Wouldn't it be enough to set a couple of baselines? While we can't set the color, this would be cleaner and easier for us. What do you think?

image

**Comment by Svn-Sp** [comment]
Could you send a link please?

**Comment by rolandgeider** [comment]
Sure!

https://github.com/wger-project/wger/blob/46f416ad0520a3db355f928b972cb2e84147bf56/wger/nutrition/static/js/nutrition.js#L114

https://github.com/metricsgraphics/metrics-graphics/wiki/Graphic#wiki-baselines

**Comment by rolandgeider** [comment]
Did you manage to take a look?

**Comment by Svn-Sp** [comment]
Had a really busy week, I will take a look at it now!

**Comment by Svn-Sp** [comment]
Finished it! Much faster than last time XD.
Could not solve the merge conflict at AUTHOR.rst, but I am not that much of an Github expert, so it should be no problem to solve it.

**Comment by rolandgeider** [comment]
PR merged, sorry it took so long 😅

**Pull request merged**
