### PR TITLE
fix(): 404 if a trainer tries to login to a different gym

### PR DESCRIPTION
**Pull request by bradsk88**
Rather than just returning "permission denied", we can interpret this scenario
as a "failure to look up a user with that gym/user ID combo".

This should give users the information they need to self-recover, while not
leaking any other sensitive details.

Fixes: #585

### Proposed Changes

**Before**: Scary "permission denied" page
simplescreenrecorder-2021-03-07_21 00 45

**After**: Helpful 404 page with explanation
simplescreenrecorder-2021-03-07_20 45 28

### Please check that the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] New python code has been linted with with flake8 (``flake8 --config .github/linters/.flake8``)
and isort (``isort``) 
- [x] Added yourself to AUTHORS.rst

### CODE REVIEW

**Comment by bradsk88** [comment]
I should note that I think the "real" fix is probably to grey out the "log in as user" button if there is a gym ID mismatch.

But, I figured it was a good practice to address this at the handler-level first.

**Comment by bradsk88** [comment]
`test_logout` is failing, but I honestly can't tell what that test is supposed to be asserting.

https://github.com/bradsk88/wger/blob/505637579cc159c556518a8c1d11782d10f24142/wger/gym/tests/test_user.py#L239-L248

If someone can clarify, I'd be happy to try and fix it.

**Comment by rolandgeider** [comment]
Nice! You are right that we should hide the button, but this is also a useful usability improvement.

The tests check that after logging in as user 2, the trainer identity is stored in the session and deleted after returning to the own account

**Comment by bradsk88** [comment]
@rolandgeider Should be good to go.  Just had my mocks set up incorrectly.

**Comment by rolandgeider** [comment]
Awesome, thanks!

**Pull request merged**
