### PR TITLE
Angular timer to fix #171

### LINKED ISSUE #171: Use angularJS for timer page
The timer page is the perfect example of a SPA, instead of the current JS mess, this should be rewritten with angularJS. There is a current work in progress in the angular_timer branch.

Implementing this issue would also pave the road to fixing #64

### PR DESCRIPTION
**Pull request by murphyalexandre**
I'm opening this up so we can discuss the issue and the code that will fix it.

I'm guessing you want a countdown running up for the exercises and down for the pauses in the bottom of the timer screen, am I right ?

### CODE REVIEW

**Comment by rolandgeider** [comment]
Thanks for opening this.

As a first step I just wanted to "port" the current logic to angular without any new logic. Once that is done, we'd take a look at #64 and see which ideas make sense and implement those. This is mainly just to prevent feature creep, something I'm often guilty of doing, but wanted to avoid here.

**Comment by murphyalexandre** [comment]
@rolandgeider Mind taking a look and telling me if I'm missing anything so I can add everything before styling it up ?

**Comment by rolandgeider** [comment]
Looking good! I like the slight animation on the progress bar. The only thing missing is that after finishing the last step, you should have a dialog to save your impressions, the API endpoint is ``workoutsession`` (the start time and end time are set internally, not by the user)

bildschirmfoto am 2016-01-14 um 10 43 47

**Comment by murphyalexandre** [comment]
I added the last page, but it still needs some love, like keeping a constant timer and using a dropdown for the impressions.

**Pull request closed without merging**
