### PR TITLE
Replace __all__ with explicit field lists in serializers and forms. #580

### PR DESCRIPTION
**Pull request by klu17**
### Proposed Changes

  - I replaced` __all__` with field lists that I created from information that I found in models.py files. Issue #580

### Please check that the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] New python code has been linted with with flake8 (``flake8 --config .github/linters/.flake8``)
and isort (``isort``) 
- [x] Added yourself to AUTHORS.rst

### Other questions

* Does this PR introduce a breaking change such as a database migration? (i.e.
what changes might users need to make in their running application due to
this PR?)
No.

### CODE REVIEW

**Comment by klu17** [comment]
I noticed that tests test editing and creating of instances of models like Gym. Should the tests pass as is? If so, I will remove extra fields from the field lists that I have added. ... I wasn't sure if I should update the tests because this is neither a bug fix or a new feature. Additionally, I am unsure of what the desired functionality is? 

For example, when creating a new Gym in the past, the test passes when a user provides a value for the name field. A Gym has other fields too like phone, email, owner, etc.

**Comment by rolandgeider** [comment]
That was quick! :)

Good question. At least for the non-editable fields setting them to read-only would probably fix this (we might have to change that in the future for the flutter application). And the tests for the gym are alright the way they are, it's not necessary to test for every possible combination

**Comment by klu17** [comment]
@rolandgeider Should be ready for review.

**Comment by rolandgeider** [comment]
Thanks!

**Pull request merged**
