### PR TITLE
[WIP] 'build frontend' feature

### PR DESCRIPTION
**Pull request by romansp**
Work in progress for 'build frontend' feature:
- [x] Add `gulp` and rework `bower` integration
- [x] Add `watch` task and Browsersync
- [ ] Setup less compilation
- [ ] Setup assets minification
- [ ] Update assets usages in templates
- [ ] Clean up and refactor

### CODE REVIEW

**Comment by rolandgeider** [comment]
I just took a look at this on my development machine, everything seems to work fine :)

**Comment by rolandgeider** [comment]
@romansp how is everything? Survived the New Year? :)

Do you think you could find the time for the rest of the items here? @murphyalexandre mentioned it would help to have these tools in place for issue #171. I have now 2 weeks free so if I can help you in any way, just ask

**Comment by romansp** [comment]
Hi, @rolandgeider. Everything just fine, New Year was perfect. How was yours? 

Regarding this PR: I've been very busy lately, so couldn't finish it earlier. I really appreciate your help and think I will finish PR during the upcoming week. Really not much work has left. I will ask for help if any issues arise.

**Comment by rolandgeider** [comment]
Great to hear that, mine was great as well (I catched a cold afterwards, but nothing bad, hehe).

**Comment by romansp** [comment]
Hi, @rolandgeider. Unfortunately, I'm still out of spare time to finish this PR. Full-time job and master's degree paper demands too much of it. Most likely, I will return back to PR not earlier than in late February :disappointed:.

If someone wants to grab it, use https://github.com/romansp/wger/tree/build-frontend branch as reference and starting point.

**Comment by rolandgeider** [comment]
Hi! Sorry for not answering earlier, my SSD first started acting strange and recently crashed completely. Don't worry about not being able to do this sooner, I'm not your boss! ;)

**Comment by petervanderdoes** [comment]
What's the purpose of this? I'm asking so I know what to do if/when I pick this up?

What's meant by "Build Frontend"?

**Comment by rolandgeider** [comment]
Some of the features have already been implemented (e.g. the JS hinter) and others are implemented server side (the JS and CSS minimiser) and work really well. In order to clean up a bit the issue tracker, I'll close this issue now. It can be re-opened or a new one opened if the need for further optimisations or tools arises

**Pull request closed without merging**
