### PR TITLE
implementing jwt token for rest api

### LINKED ISSUE #1047: Add support for JWT
We should add support for Json Web Tokens to access the API

https://github.com/jazzband/djangorestframework-simplejwt

### PR DESCRIPTION
**Pull request by RohanKaran**
# Proposed Changes

- closes #1047  
- Implementation of JWT using Simple JWT
- Added all relevant endpoints regarding JWT.
- But kept the login endpoint which sends a non-expiring token and also during registration it sends the same token in response. Let me know when to remove those.

## Please check that the PR fulfills these requirements

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Added yourself to AUTHORS.rst

### Other questions

* Do users need to run some commmands in their local instances due to this PR
  (e.g. database migration)?
  No

### CODE REVIEW

**Comment by rolandgeider** [comment]
Great! I would leave the older login endpoints for the moment, there are probably other people that are using them, but should add some deprecation warning to the docs. 

Could you add some kind of usage for this? We can basically use the same ones from their docs https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html#usage

**Comment by RohanKaran** [comment]
@rolandgeider Can you specify where I would add the usage for jwt endpoints ?

**Comment by rolandgeider** [comment]
The api docs are in `sofware/templates/api.html` (at least for the moment, they should be reworked one of these days)

**Comment by RohanKaran** [comment]
@rolandgeider docs added

**Comment by rolandgeider** [comment]
great, I will try to test this today or tomorrow

**Review by rolandgeider — APPROVED** [review]

**Comment by rolandgeider** [comment]
This looks great thanks.

We're very close to releasing these next days so would wait to merging this since it is a rather important change. The PR is approved so it counts towards hacktoberfest (and I'll merge it next week or so when we've released anyway)

**Comment by RohanKaran** [comment]
Cool 👍 My hactoberfest task is already completed though 😃.

**Pull request merged**
