### PR TITLE
Configuring django axes

### LINKED ISSUE #1096: No protection against bruteforce attacks on login page
At the moment there is no protection against brute force attacks on the login page, while not a priority it would be nice if we could do something about it.

* https://github.com/jazzband/django-defender
* https://github.com/jazzband/django-axes

### PR DESCRIPTION
**Pull request by RohanKaran**
# Proposed Changes

- Added configuration for django-axes
- Added comments in ```wger/settings_global.py:270``` regarding usage of redis based cache.
- closes #1096 

## Please check that the PR fulfills these requirements

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added yourself to AUTHORS.rst

### Other questions

* Do users need to run some commmands in their local instances due to this PR
  (e.g. database migration)?
- ```python manage.py migrate```

### CODE REVIEW

**Comment by RohanKaran** [comment]
Just these settings or all the settings related to axes ???

**Comment by rolandgeider** [comment]
I'd say only these, the others can stay the same for all Installations

**Comment by RohanKaran** [comment]
> I'd say only these, the others can stay the same for all Installations

done

**Comment by rolandgeider** [comment]
Merged, thanks!

**Pull request merged**
