### PR TITLE
Total authors history bugfix

### PR DESCRIPTION
**Pull request by AdamPetik**
# Proposed Changes
@rolandgeider I realised, union does not modify the original set but returns new one. So here is fix for collecting author histories.

### CODE REVIEW

**Comment by rolandgeider** [comment]
Good catch!

**Comment by rolandgeider** [comment]
oh, BTW, the crowdsourcing branch was recently merged, can you edit the PR so it merges into master? (or open a new one if that's not possible, I'm not sure right now)

**Comment by AdamPetik** [comment]
sure

**Comment by rolandgeider** [comment]
Thanks :)

**Pull request merged**
