### PR TITLE
Return muscle image URLs from model (fixes #547)

### LINKED ISSUE #547: Return image URL on muscle endpoint
The muscle endpoint should also return the URLs for the muscle images and the backgrounds (probably the exercise endpoint as well). Needs to check whether we can access the URL when the static files are hosted on AWS or such

### PR DESCRIPTION
**Pull request by gengkev**
### Proposed Changes

Each muscle is associated with a primary and secondary image, which are used if it is the primary or secondary muscle in an exercise, respectively. The previous code computed the URLs of these images in the `render_muscle()` function. This commit generalizes this slightly by moving that calculation to the muscle model instead.

Question: Does this address the intent of the original issue #547, or should additional refactoring be made? For instance, we could use an `ImageField`, similar to `ExerciseImage`, so that muscle images can be uploaded and edited by the admin (rather than only using the fixtures).

### Please check that the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] New python code has been linted with with flake8 (``flake8 --config .github/linters/.flake8``)
and isort (``isort``) 
- [x] Added yourself to AUTHORS.rst

### Other questions

* Does this PR introduce a breaking change such as a database migration? (i.e. what changes might users need to make in their running application due to this PR?)
  No

### CODE REVIEW

**Comment by rolandgeider** [comment]
This is fine, having an admin interface for the muscles would be too much work for something that is basically never used.

The only change I'd suggest is adding the muscle fields to MuscleSerializer (explicitly, instead of __all__, which is always sensible to do)

**Comment by gengkev** [comment]
Thanks! Just to make sure, would the reason for that be to make sure that only the two actual properties (name and is_front) are serialized, while the url properties added by this change are not?

**Comment by rolandgeider** [comment]
no, add the new url properties as well, it's useful having the background URLs when using the API

**Comment by gengkev** [comment]
Thanks, that makes sense! I assumed that "serializer" meant the purpose was for storing data, but it makes more sense if the data is being used as an API instead.

I've changed the MuscleSerializer to do that, and tried to modify the `MuscleApiTestCase` to verify that the correct URLs are in fact being returned.

**Comment by rolandgeider** [comment]
Looks good, thanks!!

**Comment by gengkev** [comment]
I updated the PR to fix the merge conflicts!

**Comment by rolandgeider** [comment]
Merged, thanks!

**Pull request merged**
