### PR TITLE
Body Measurements Implementation [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by DandyDeveloper**
Template taken from Weight model with amendments pending but baseline prepped. To do: 

- [ ] Cater specific measurements 
- [ ] Alter template to include images that depend on user gender (???)
- [ ] Ensure weight entities are removed/replaced with body measurements
- [ ] Allow daily logging, but keep latest log appended to user profile (read only).

Creating PR now. Moving onto some small bug fixes as many issues outstanding.

### CODE REVIEW

**Comment by EGUltraTM** [comment]
Are you maybe still working on this? Its the only thing which would be missing in wger :)

**Comment by AaronFixer** [comment]
@EGUltraTM It's somewhat on my list, but I'm so preoccupied with my job, and other projects. I don't have much time to work on this right now.

**Comment by Zoink5** [comment]
Would love to see this feature - it would make wger more complete.

**Comment by DandyDeveloper** [comment]
For the time being, since this repo isn't really being maintained from what I can tell. I won't do anything more with this. I may come back to the PR in future when I get some free time.

Personal life / working life mean I just don't have time to work on this right now.

**Pull request closed without merging**
