### PR TITLE
Updated italian translation

### PR DESCRIPTION
**Pull request by lediable**
modified:   wger/locale/it_IT/LC_MESSAGES/django.mo
	modified:   wger/locale/it_IT/LC_MESSAGES/django.po
	modified:   wger/settings_global.py
        new file:   wger/core/static/images/icons/flag-it.svg

### CODE REVIEW

**Comment by rolandgeider** [comment]
Thanks! I'll try to find some time this evening to look at this.

Can you indent the line in settings_global with spaces? Then the checks won't fall.

**Comment by rolandgeider** [comment]
So I managed to take a took a look at this. I'd like to activate new languages when the content is  completely or almost completely translated, then it makes a better impression (obviously it's perfectly OK when there's a word here or there missing).

I saw that you added yourself as a translator in transifex, you can keep translating there. I usually download all the translations from transifex when I release a new version or when the language was completed. I can also install them to the preview server, in case you want to see them in context, it's not always clear what the strings mean.

**Comment by lediable** [comment]
HI!

Ok, I uploaded the .po file into transifex :)
When I translate I am using always two server: one in english and the other one with my translation so I can see the strings into the context and make a better translation.

However I will try to complete the Italian translation!

**Comment by rolandgeider** [comment]
Great! If you have already a running local installation, then it's much easier. In any case if you have questions or suggestions, just ping me :)

**Pull request closed without merging**
