### PR TITLE
Fix set slider updating problem and Changed UUID field type

### PR DESCRIPTION
**Pull request by gmmoraes**
#374
#364

in wger/wger/templates/set/add.html
I have substituted the span tag from the form for an output tag.

in wger/exercises/models.py 
I changed the uuid field from CharField to UUIDField.

### CODE REVIEW

**Comment by rolandgeider** [comment]
Thanks for the PR, but you shouldn't combine different issues in a single pull request (unless they are related, obviously). I'll review this during the weekend

**Comment by gmmoraes** [comment]
Ok! My bad.

Do you want me to close this PR and make two individual PR fot both issues?

Have a nice holliday and weekdend,

Thanks for the PR, but you shouldn't combine different issues in a single
pull request (unless they are related, obviously). I'll review this during
the weekend

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wger-project/wger/pull/377#issuecomment-293922365>, or mute
the thread

**Comment by rolandgeider** [comment]
That would be best 👍

**Comment by gmmoraes** [comment]
Ok!
Em 13/04/2017 12:47, "Roland Geider" <notifications@github.com> escreveu:

**Comment by rolandgeider** [comment]
Thanks! Closing this PR to keep things clear, just open new ones for the separate issues

**Pull request closed without merging**
