### PR TITLE
Fixed set slider updating problem

### PR DESCRIPTION
**Pull request by gmmoraes**
#374

in wger/wger/templates/set/add.html
I have substituted the span tag from the form for an output tag.

### CODE REVIEW

**Comment by rolandgeider** [comment]
This will update the number of sets shown on the side, but not the forms. Have you tried changing the JS file referenced in #374  to ``on('input' ...``? Perhaps this is enough

**Comment by petervanderdoes** [comment]
Two things:
- Check the Travis error. It failed on a coding standard.
- It works on Firefox but it doesn't work for me in Chrome Version 58.0.3029.96

**Comment by petervanderdoes** [comment]
Nevermind the not working in Chrome. The original JS was cached :/

**Comment by gmmoraes** [comment]
Thank you peter, I have changed the file in order to pass the travis ci test.

**Comment by petervanderdoes** [comment]
Awesome. Thank @gmmoraes . I'll review it and merge it.

**Comment by petervanderdoes** [comment]
Merge per commit 26cdf5e68e84df460fa4bcba89236850a7b201d9

**Pull request closed without merging**
