### PR TITLE
Changed Layout of Feature Page

### PR DESCRIPTION
**Pull request by DeveloperMal**
The layout of the feature page made the view of the images small, cluttered, and hard to see. I've made changes that make the images easier to see on devices such as laptop/desktop computers.

## Old Layout:

wgerlayoutoldbig

## New Layout:
wgerlayoutnewbig

### CODE REVIEW

**Comment by rolandgeider** [comment]
Thanks! I'll try to merge it this evening

**Comment by rolandgeider** [comment]
Ah, can you add yourself to the AUTHORS file?

**Comment by DeveloperMal** [comment]
No problem, Done.

**Comment by rolandgeider** [comment]
Sorry I didn't answer earlier, I'm half on vacation and probably won't have much internet the next week. I was thinking that if we redesign the features page, we could perhaps do something [like these examples](https://startbootstrap.com/template-categories/all). What do you think?

**Comment by DeveloperMal** [comment]
Its fine. I think using themes would be good. It would also help with mobile. Looking at the ones on the site Im really liking [this one](https://blackrockdigital.github.io/startbootstrap-landing-page/) and [this one](https://blackrockdigital.github.io/startbootstrap-one-page-wonder/). Both of those resemble a lot of what I was trying to do with new layout. Did you have any themes you had in mind?

**Comment by rolandgeider** [comment]
Yeah, I like the first one. I was also thinking about [this one](https://blackrockdigital.github.io/startbootstrap-agency/) (probably without the portfolio or team sections)

**Comment by rolandgeider** [comment]
I have tried one of those templates, you can pull from my new-featurepage branch (you'll need to ``git pull https://github.com/wger-project/wger.git new-featurepage`` for some reason I can't send you a PR), what do you think? I have removed a lot of text and there's still work to do but I'd say it looks like an improvement :)

**Comment by DeveloperMal** [comment]
Definitely a huge improvement. Kudos on finding that header image, its looks fantastic. Also kudos on cropping the the images showing the different features. If you want I can work on cleaning it up a bit by making the white text more readable. Changing the yellow primary color to a blue one closed to the wger blue. And a couple of more things.

**Comment by rolandgeider** [comment]
Sure go ahead! I have still left the fonts from the template, we'd have to change that in the CSS as well. It'd be also OK to change the texts, now that there's less of them we can have something that makes more sense (I was always wary of changing them because then there's a lot of translation work to do and I preferred to have a translated landing page). And you are right, that picture is even CC-0, so public domain!

**Comment by DeveloperMal** [comment]
Alright then Ill get started!

**Comment by DeveloperMal** [comment]
Do you prefer to keep the share button that is on the top right of the page? I was going to remove it completely fix the spacing issues its causing but if you want it on the page I could adjust it to a different spot.

**Comment by rolandgeider** [comment]
No, you can move it somewhere else in the page

**Comment by rolandgeider** [comment]
Hi!

Just a head up, I'll be away the following week, I'll have internet and will be able to answer here on the issue tracker but won't be able to test any code or such

**Comment by DeveloperMal** [comment]
Alright then! I should have all the clean up work done by the end of the week.

**Comment by rolandgeider** [comment]
This looks good from my side, I still want to change some details like the texts and fonts, but I can do that after I merge your PR. Do you want to do something else or are you done from your side?

**Comment by DeveloperMal** [comment]
Yeah. You can go ahead and merge the PR. I'm finished with everything on my side.

**Comment by rolandgeider** [comment]
Merged this and applied my changes, but will still wait a bit till I update wger.de, thanks @DeveloperMal for starting this, I had thought about updating the landing page, but never got around to actually doing it

**Comment by DeveloperMal** [comment]
Thanks you very much! I really enjoyed working on this PR and working on wger. I cannot wait to do more contributions in the future.

**Comment by rolandgeider** [comment]
Great to hear that! :+1:

**Pull request merged**
